server:
  port: ${PORT:8080}
spring:
  application:
    name: kameleoon-trial-service
  datasource:
    url: ${DB_URL:jdbc:h2:./kameleoon_db;DB_CLOSE_ON_EXIT=FALSE}
    driverClassName: org.h2.Driver
    username: ${DB_USERNAME:sa}
    password: ${DB_PASSWORD:password}
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.H2Dialect
  liquibase:
    change-log: classpath:db/migration/v1/changelog.yaml
  jackson:
    mapper:
      accept-case-insensitive-enums: true
logging:
  level:
    com.example.kameleoon: debug
springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /api-docs
jwt:
  secret: ${JWT_SECRET:6150645367566B59703373357638792F423F4528482B4D6251655468576D5A71}